/* CREATE TYPE quadrant AS ENUM('NW', 'NE', 'SW', 'SE'); */



CREATE table IF NOT EXISTS stormWindMeasurment(
   id INT GENERATED BY DEFAULT AS IDENTITY,
   radiusMaxWindID INT,    
   quadrant quadrant,
   radius double precision,

   PRIMARY KEY(id),
   CONSTRAINT fk_storm_record_id
    FOREIGN key(radiusMaxWindID)
      REFERENCES stormReading(id) ON DELETE CASCADE
);
