/* Create Enumeration types for the table */
DO $$ BEGIN
    CREATE TYPE stormRecordIdentifier AS ENUM ('C', 'G', 'I', 'L', 'P', 'R', 'S', 'T', 'W', '');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE stormType AS ENUM('TD', 'TS', 'HU', 'EX', 'SD', 'SS', 'LO', 'WV', 'DB', '');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE quadrant AS ENUM('NW', 'NE', 'SW', 'SE', '');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;



CREATE table IF NOT EXISTS stormReading(
   id INT GENERATED BY DEFAULT AS IDENTITY,
   stormID int,
   recordTime timestamp,  
   recordId stormRecordIdentifier,
   status stormType,
   lat double precision,
   lng double precision,
   overallQuadrant quadrant, 
   maxSustainedWind double precision,
   maxWindRadius double precision,
   minimumPressure double precision, 
   PRIMARY KEY(id),
   CONSTRAINT fk_storm_id
    FOREIGN key(stormID)
      REFERENCES stormIdentification(id) ON DELETE CASCADE
);


