CREATE table IF NOT EXISTS stormIdentification(
   id INT GENERATED BY DEFAULT AS IDENTITY,
   basin VARCHAR(2),
   atcfCycloneNumber SMALLINT,
   year INT, 
   name VARCHAR(10), 
   UNIQUE (basin, atcfCycloneNumber, year, name),
   PRIMARY KEY(id)
);
